listenPort: 3000
services:
  authentication:
    name: authentication
    transport: TCP
    host: ot_authentication
    port: 3001
  profile:
    name: profile
    transport: TCP
    host: ot_profile
    port: 3002
  social:
    name: social
    transport: TCP
    host: ot_social
    port: 3003
  tasks:
    name: tasks
    transport: TCP
    host: ot_tasks
    port: 3004
  asset:
    name: asset
    transport: TCP
    host: ot_asset
    port: 3005
  project_planning:
    name: project_planning
    transport: TCP
    host: ot_project_planning
    port: 3006
  chat_collector:
    name: chat_collector
    transport: TCP
    host: ot_chat_collector
    port: 3007
  telos_docs_service:
    name: telos_docs_service
    transport: TCP
    host: ot_telos_docs_service
    port: 3008
  ai_orchestration:
    name: ai_orchestration
    transport: TCP
    host: ot_ai_orchestration
    port: 3010
  blogging:
    name: blogging
    transport: TCP
    host: ot_blogging
    port: 3011